import type { Metadata } from "next";
import "@/assets/styles/global.css";
import { AOSInit } from "@/app/components/aos";
import { LayoutFooter, LayoutHeader } from "@/app/components/home";

export const metadata: Metadata = {
  title: "iDarkQ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AOSInit />
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0"
        />
      </head>
      <body className="relative">
        <LayoutHeader />
        <main>{children}</main>
        <LayoutFooter />
      </body>
    </html>
  );
}
