import type { Metadata } from "next";
import "@/assets/styles/global.css";
import { AOSInit } from "@/app/components/aos";
import { Header } from "@/app/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <AOSInit />
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0&icon_names=home,keyboard_arrow_down,menu"
        />
      </head>
      <body>
        <div className="relative">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
